#!/usr/bin/env python3
"""Mechanically crop approved outfit PNGs and emit compact RGB565 sprites.

Requires Pillow. No art is generated: largest connected character component,
nearest-neighbor resize, then RGB565 quantization. Standalone weather icons are
excluded. The generated header records source hashes and crop coordinates.
"""
import argparse
from collections import deque
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ESP32 = Path(__file__).resolve().parents[2]
PROJECT = ESP32.parent
GRID = 96
MAX_HEIGHT = 72
MAX_WIDTH = 82


def character_crop(source):
    rgba = Image.open(source).convert("RGBA")
    image = Image.new("RGB", rgba.size, "black")
    image.paste(rgba, mask=rgba.getchannel("A"))
    red, green, blue = image.split()
    bright = ImageChops.lighter(ImageChops.lighter(red, green), blue)
    mask = bright.point(lambda value: 255 if value > 18 else 0)
    # Bridge the artwork's black pixel outlines without joining separate icons.
    radius = max(1, round(max(image.size) / 512))
    dilated = mask.filter(ImageFilter.MaxFilter(radius * 2 + 1))
    width, height = image.size
    unseen = bytearray(dilated.tobytes())
    largest = []
    for seed, value in enumerate(unseen):
        if not value:
            continue
        pending = deque([seed])
        unseen[seed] = 0
        component = []
        while pending:
            at = pending.pop()
            component.append(at)
            x, y = at % width, at // width
            for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < width and 0 <= ny < height:
                    neighbor = ny * width + nx
                    if unseen[neighbor]:
                        unseen[neighbor] = 0
                        pending.append(neighbor)
        if len(component) > len(largest):
            largest = component
    if not largest:
        raise ValueError("no visible character in %s" % source)
    keep = bytearray(width * height)
    for at in largest:
        keep[at] = 255
    keep = Image.frombytes("L", image.size, bytes(keep))
    original_content = ImageChops.multiply(mask, keep)
    box = original_content.getbbox()
    # Composite the original pixels, including dark outlines, rather than the mask.
    isolated = Image.composite(image, Image.new("RGB", image.size), keep)
    return isolated.crop(box), box


def convert(catalog, assets):
    entries = json.loads(Path(catalog).read_text())
    if len(entries) != 13 or len({entry["id"] for entry in entries}) != 13:
        raise ValueError("expected thirteen unique approved outfit IDs")
    result = []
    for entry in entries:
        source = Path(assets) / entry["file"]
        crop, box = character_crop(source)
        scale = min(MAX_WIDTH / crop.width, MAX_HEIGHT / crop.height)
        size = (max(1, round(crop.width * scale)), max(1, round(crop.height * scale)))
        sprite = crop.resize(size, Image.Resampling.NEAREST)
        rgb = sprite.tobytes()
        pixels = [(r >> 3) << 11 | (g >> 2) << 5 | (b >> 3)
                  for r, g, b in zip(rgb[0::3], rgb[1::3], rgb[2::3])]
        result.append(dict(entry, box=box, sprite=sprite, pixels=pixels,
                           sha256=hashlib.sha256(source.read_bytes()).hexdigest()))
    return result


def write_header(entries, output):
    lines = ["/* Generated by tools/muse/wardrobe_assets.py from approved user artwork.",
             " * Mechanical crop/nearest-neighbor conversion only; do not edit pixels here. */",
             "#pragma once", "#include <stdint.h>",
             "#define MUSE_WARDROBE_GRID %d" % GRID,
             "#define MUSE_WARDROBE_ASSET_COUNT %d" % len(entries),
             "typedef struct { const char *id; uint8_t width, height; const uint16_t *pixels; } muse_wardrobe_asset_t;"]
    for i, entry in enumerate(entries):
        lines += ["/* %s; source sha256 %s; crop %s */" % (entry["file"], entry["sha256"], entry["box"]),
                  "static const uint16_t muse_wardrobe_pixels_%d[] = {" % i]
        pixels = entry["pixels"]
        for at in range(0, len(pixels), 16):
            lines.append("    " + ",".join("0x%04x" % value for value in pixels[at:at + 16]) + ",")
        lines.append("};")
    lines.append("static const muse_wardrobe_asset_t muse_wardrobe_assets[] = {")
    for i, entry in enumerate(entries):
        lines.append('    {"%s", %d, %d, muse_wardrobe_pixels_%d},' %
                     (entry["id"], entry["sprite"].width, entry["sprite"].height, i))
    lines += ["};", ""]
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


def preview(entries, directory):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    sheet = Image.new("RGB", (4 * 288, 4 * 320), "#141414")
    draw = ImageDraw.Draw(sheet)
    for i, entry in enumerate(entries):
        sprite = entry["sprite"]
        card = Image.new("RGB", (GRID, GRID))
        card.paste(sprite, ((GRID - sprite.width) // 2, 91 - sprite.height))
        card = card.resize((288, 288), Image.Resampling.NEAREST)
        card.save(directory / (entry["id"] + ".png"))
        x, y = i % 4 * 288, i // 4 * 320
        sheet.paste(card, (x, y + 24))
        draw.text((x + 8, y + 4), entry["id"], fill="white")
    sheet.save(directory / "contact.png")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=PROJECT / "assets/weather/catalog.json")
    parser.add_argument("--assets", type=Path, default=PROJECT / "assets/weather")
    parser.add_argument("--output", type=Path, default=ESP32 / "components/muse/wardrobe_assets.h")
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    entries = convert(args.catalog, args.assets)
    write_header(entries, args.output)
    if args.preview_dir:
        preview(entries, args.preview_dir)
    print("Converted %d approved outfits; %d RGB565 bytes; %s" %
          (len(entries), sum(len(entry["pixels"]) * 2 for entry in entries), args.output))
    for entry in entries:
        print("%s: crop %s -> %s" % (entry["id"], entry["box"], entry["sprite"].size))


if __name__ == "__main__":
    main()
